version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - ../backend:/app

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
